import type { Metadata } from "next";

import "@/app/globals.css";

export const metadata: Metadata = {
  title: "Panel",
  description: "Generated by create next app",
};

export default function UpdateLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-amber-400 flex p-5 justify-center min-h-screen">
      {children}
    </div>
  );
}
