import type { Metadata } from "next";

import "@/app/globals.css";

export const metadata: Metadata = {
  title: "DashBoard",
  description: "Generated by create next app",
};

export default function PanelLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className="bg flex flex-col justify-center">{children}</div>;
}
